version: '3'
services:
  db:
    image: mysql:5.7
    container_name: ats-mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: app
        MYSQL_USER: user
        MYSQL_PASSWORD: password
    ports:
       - "3307:3306"
    volumes:
      - ats-datavolume:/var/lib/mysql
  app:
    build: .
    command: rails s -p 6000 -b '0.0.0.0'
    container_name: ats-server
    volumes:
      - ".:/app"
    ports:
       - "6001:6000"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_USER: user
      DB_NAME: app
      DB_PASSWORD: password
      DB_HOST: db
volumes:
  ats-datavolume:
